services:
  # PHP + Apache
  php-apache: 
    build:
      dockerfile: Dockerfiles/PhpApache
    volumes:
      - ./www:/var/www
    ports:
      - 9000:80                   # port 8000
    depends_on:
      - database

  # database
  database: 
    build:
      dockerfile: Dockerfiles/Database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strongout
      MYSQL_USER: admin
      MYSQL_PASSWORD: heslo
    ports:
      - 9906:3306

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080                 # port 8080